rails/config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :chapters
  get 'chapter/index'
  mathjax 'mathjax'
  root 'chapters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/app/controllers/chapters_controller.rb
# coding: utf-8
require 'cgi'

class ChaptersController < ApplicationController
    # def index
    #     preface = Chapter.find_by title: 'Webpreface'
    #     @preface_html = preface.html_content
    # end

    # The following methods are better put in the model rather than the controller
    # I already copied them there
    def remove_tag_name(doc, tag)
        doc.search(tag).each do |node|
            node.after(node.children)
            node.remove
        end
    end

    def replace_tag(doc, tag, text)
        doc.search(tag).each do |node|
            node.after(text)
            node.remove
        end
    end

    def js_scheme_output(doc, tag)
      doc.search(tag).each do |node|

        wrapper_div = doc.create_element("div", :class => "code")

        node.before(node.children)
        
        node.remove
        end
    end
    
    def show
        @chapter = Chapter.find(params[:id])
        content = @chapter.xml_content
        order = @chapter.order
        ex_start_index = @chapter.exercise_start_number


        
        # String substitutions
        content = content.gsub('\\LaTeX','$\\rm\\LaTeX$');
        content = content.gsub('^$\langle','$\langle');
        content = content.gsub('\rangle$^','\rangle$');
        xml_doc = Nokogiri::XML(content)

        # Remove comments
        xml_doc.xpath('//comment()').each { |comment| comment.remove }

        # Remove tags according to textbook version
        if (LANGUAGE_VERSION == "javascript")
            xml_doc.search('SCHEME').remove
            remove_tag_name(xml_doc, "JAVASCRIPT")
        else
            xml_doc.search('JAVASCRIPT').remove
            remove_tag_name(xml_doc, "SCHEME")
        end

        if (!xml_doc.at('NAME').nil?)
            @title = @chapter.chapter_number + " " + xml_doc.at('NAME').text
            xml_doc.at('NAME').remove
        else
            @title = @chapter.title
        end

        # Wrap each <p>...</p> in a <a name="§n"></a> to serve as a permalink for each paragraph
        paragraph_number = 0
        xml_doc.search("TEXT").each do |p|
          paragraph_number += 1
          permalink_wrap(xml_doc, p, "p#{paragraph_number}")
        end

        # Figure without img/with link to gif
        xml_doc.search('FIGURE').each do |figure|
            label = figure.at('LABEL')
            if (!label.nil? && !label['NAME'].nil?)
                full_name = label['NAME']
                kind, ref_name = full_name.split(':')
                required = Reference.find_by(kind: kind, name: ref_name)
                if (!required.nil?)
                    cap = figure.at('CAPTION')
                    if (!cap.nil?)
                        # fig_prefix = Nokogiri::XML::Node.new('b', xml_doc)
                        fig_prefix = xml_doc.create_element('b')
                        cap.children.first.add_previous_sibling(fig_prefix)
                        link = xml_doc.create_element("a", 'Figure ' + required.numbering + ' ',
                                :class => "caption",
                                :id => "fig_" + required.numbering,
                                :href => "#fig_" + required.numbering)
                        fig_prefix.add_child(link)
                    end
                end 
            end
            if (!figure['src'].nil?)
                figure.name = 'img'
            end
        end

        xml_doc.search('EXERCISE').each do |ex|
            label = ex.at('LABEL')
            if (!label.nil? && !label['NAME'].nil?)
                full_name = label['NAME']
                kind, ref_name = full_name.split(':')
                required = Reference.find_by(kind: kind, name: ref_name)
                if (!required.nil?)
                    ex_numbering = required.numbering
                end
            else
                ex_numbering = order[0] + '.' + ex_start_index.to_s
            end
            b = xml_doc.create_element("b")
            ex.children.first.add_previous_sibling(b)
            a = xml_doc.create_element("a", "Exercise " + ex_numbering + " ",
                :class => "exercise-number permalink",
                :id => "ex_" + ex_numbering)
            b.add_child(a)
            ex_start_index += 1

            no_solution_count = 1
            solution = ex.at('SOLUTION')
            if (solution.nil?)
                solution_div = xml_doc.create_element("div", :class => 'Solution')
                solution_btn_div = xml_doc.create_element("div", :class => "solution_btn")

                solution_btn = xml_doc.create_element("button", "Add solution",
                    :class => "btn btn-secondary solution_btn",
                    :href => "#no_solution_#{@chapter.id}_#{no_solution_count}_div")
                solution_btn["data-toggle"] = "collapse"
                solution_content = xml_doc.create_element("div",
                                       :class => 'solution_content collapse',
                                       :id => "no_solution_#{@chapter.id}_#{no_solution_count}_div")

                solution_content.add_child("There is currently no solution available for this exercise. This textbook adaptation is a community effort. Do consider contributing by providing a solution for this exercise, using a Pull Request in <LINK address='https://github.com/source-academy/sicp'>Github</LINK>.")
                solution_div.add_child(solution_btn_div)
                solution_div.add_child(solution_content)
                solution_btn_div.add_child(solution_btn)
                ex.add_child(solution_div)
                no_solution_count += 1

            end            

            permalink_wrap(xml_doc, ex, "ex_#{ex_numbering}")
        end

        
        # ref
        xml_doc.search("REF").each do |ref|
            if (!ref['NAME'].nil?)
                full_name = ref['NAME']
                kind, ref_name = full_name.split(':')
                required = Reference.find_by(kind: kind, name: ref_name)
                if (!required.nil?)
                    # ref.content = required.numbering
                    linked_chapter = Chapter.find_by(order: required.order)
                    if (!linked_chapter.nil?)
                        if kind == "sec"
                            link = linked_chapter.id.to_s
                        elsif kind == "ex"
                            link = linked_chapter.id.to_s + "#ex_" + required.numbering
                        else
                            link = linked_chapter.id.to_s + "#fig_" + required.numbering
                        end
                        a = xml_doc.create_element("a", required.numbering,
                            :class => "superscript",
                            :id => order + "-" + kind + "-link-" + required.numbering,
                            :href => link)
                        # ref.next = a
                        ref.add_child(a)
                    else
                      ref.add_child(xml_doc.create_element("strong", "No linked chapter"))
                    end
                else
                  ref.add_child(xml_doc.create_element("strong", "Cound not find label for #{full_name}"))
                end    
            else
              ref.add_child(xml_doc.create_element("strong", "Broken REF tag"))
            end    
        end

        # Renaming tags
        # divs
        xml_doc.search('ATTRIBUTION, CAPTION').each do |div|
                div['class'] = 'chapter-text-' + div.name
                div.name = 'div'
            end

        # spans
        xml_doc.search('AUTHOR, DATE, TITLE').each do |span|
                span['class'] = 'chapter-text-' + span.name
                span.name = 'span'
        end

        # Links
        xml_doc.search('LINK').each do |link|
            link.name = 'a'
            link['href'] = link['address']
        end

        # Headings
        # Wrap each <h>...</h> in a <a name="§n"></a> to serve as a permalink for each paragraph
        heading_number = 0
        xml_doc.search('SUBHEADING').each do |heading|
          heading.name = 'h2'
          heading_number += 1
          permalink_wrap(xml_doc, heading, "h#{heading_number}")
        end

        xml_doc.search('SUBSUBSECTION').each do |h1|
          h1.name = 'h1'
          heading_number += 1
          permalink_wrap(xml_doc, h1, "h#{heading_number}")
        end

        xml_doc.search('MATTERSECTION').each do |h1|
          h1.name = 'h1'
          heading_number += 1
          permalink_wrap(xml_doc, h1, "h#{heading_number}")
        end

        # Blockquote
        xml_doc.search('EPIGRAPH').each do |quote|
            quote.name = 'blockquote'
            quote['class'] = 'blockquote'
        end

        # text
        xml_doc.search("TEXT").each do |text|
            text.name = 'p'
        end

        # p
        xml_doc.search("P").each do |text|
            text.name = 'p'
        end

        # BR
        xml_doc.search("BR").each do |text|
            text.name = 'br'
        end

        xml_doc.search('COMMENT').remove               
        xml_doc.search('HISTORY').remove
        xml_doc.search('INDEX').remove
        xml_doc.search('LABEL').remove
        xml_doc.search('OMISSION').remove
        xml_doc.search('SCHEMEOUTPUT').remove
        xml_doc.search('SUBINDEX').remove
        remove_tag_name(xml_doc, "SPLITINLINE")

        # Using Mathjax, remove tag names
        remove_tag_name(xml_doc, "LATEX")
        remove_tag_name(xml_doc, "LATEXINLINE")

        # Formatting
        replace_tag(xml_doc, 'APOS', '\'')
        replace_tag(xml_doc, 'SPACE', '&nbsp;')
        replace_tag(xml_doc, 'WJ', '&#8288;')
        replace_tag(xml_doc, 'AACUTE_LOWER', '&aacute;')
        replace_tag(xml_doc, 'AACUTE_UPPER', '&Aacute;')
        replace_tag(xml_doc, 'AGRAVE_LOWER', '&agrave;')
        replace_tag(xml_doc, 'AGRAVE_UPPER', '&Agrave;')
        replace_tag(xml_doc, 'ACIRC_LOWER', '&acirc;')

rails/app/helpers/chapter_helper.rb
module ChapterHelper
end

rails/app/views/chapters/index.html.erb
<div class="chapter-content">

  <div class="chapter-text" >
    <%= raw @preface_html %>

    <TABLE class="tight">
	<TD  class="tight" width="70%" valign="top" align="right">
          <img class="tight" src="chapters/img_javascript/sicp.png"
	       height="auto" width="100%">
	</TD>
	<TD  class="tight" width="30%" valign="top" align="left">
	  <div class="title-text-EDITION">
	    <span class="title-text-EDITION">Mobile-friendly Web Edition</span>
	  </div>
	  <span style="vertical-align:-77%"/>
	  <BR/>
	  <div class="title-text-ALSO">
	    <span class="title-text-ALSO">also available</span><BR/>
	  </div>
	  <div class="title-text-OTHEREDITIONS">
	    <span class="title-text-OTHEREDITIONS">
	  <a href="https://sicp.comp.nus.edu.sg/sicpjs.pdf">PDF edition</a></span>
	  </div>
	  <div class="title-text-OTHEREDITIONS">
	    <span class="title-text-OTHEREDITIONS">
	  <a href="https://sicp.comp.nus.edu.sg/sicp.epub">E-book edition</a></span>
	  </div>
	</TD>
      </TR>
    </TABLE>
    
    <div class="title-text-ATTRIBUTION">
      <span class="title-text-AUTHOR">Harold Abelson and Gerald Jay Sussman<br/>with Julie Sussman</span> <span class="title-text-TITLE">authors</span>
    </div>

    <div class="title-text-ATTRIBUTION">
      <span class="title-text-AUTHOR">Martin Henz and Tobias Wrigstad<br/>with Chan Ger Hean, Feng Piaopiao, Jolyn Tan and Liu Hang</span> <span class="title-text-TITLE">adapters to JavaScript</span>
    </div>

    <h2>Content</h2>
    <div class="nav-index">
      <% Chapter.roots.all.order(:order).each do |chapter| %>
      <%= content_links(chapter, "nav-index", "index").html_safe %>
      <% end %>
    </div>
  </div>

</div>
<!--
    <%= javascript_tag "var chapter_id = 1;" %>
    -->

rails/app/views/chapters/show.html.erb
<div id="permalink-msg">
  <div class="screen">
    <div class="alert alert-success">
      <strong>Permalink copied!</strong> 
    </div>
  </div>
</div>
<div class="chapter-content">

  <div class="chapter-title">
    <div class="permalink">
      <a name="top" class="permalink"><%= @title %></a>
    </div>
  </div>
    <div class="chapter-text" >
        <%= raw @html_doc %>
    </div>

    <div class="nav">

    <% if (@chapter.id > 1) %>
        <button type="button" class="btn btn-secondary" style="background-color: #fff;">
          <%= link_to  "< Previous", chapter_url(@chapter.id - 1) %>
        </button>
    <% end %>

    <div style="flex-grow: 1;"></div>
    
    <% if (@chapter.id < Chapter.count) %>
        <button type="button" class="btn btn-secondary" style="background-color: #fff;">
          <%= link_to  "Next >", chapter_url(@chapter.id + 1), :class => "scroll-next"  %>
        </button>
    <% end %>

    <% if (@chapter.id >= Chapter.count) %>
        <div>
          <%= link_to  "", 'e', :class => "scroll-next"  %>
        </div>
    <% end %>

  </div>
  <div class="chapter_sign">
        <%= @title %>
    </div>
  <%= javascript_tag "var chapter_id = #{@chapter.id};" %>
  <div class="next-page"></div>
</div>