rails/config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :chapters
  get 'chapter/index'
  mathjax 'mathjax'
  root 'chapters#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/app/models/snippet.rb
class Snippet < ApplicationRecord
    serialize :required_snippet_names, Array
    has_many :requirements, class_name: "Requirement", foreign_key: "snippet_id"
    has_many :required_snippets, :through => :requirements

    def get_required_code
        code = ''
        self.required_snippets.each do |required|
            code += required.get_required_code
        end
        code += self.code
        return code
    end


    def get_required_function_name(all_names)
        if all_names.include? self.name
            return all_names
        end

        all_names << self.name
        self.required_snippets.each do |required|
            if all_names.include? required.name
                next
            else
                all_names = required.get_required_function_name(all_names)
            end
        end
        all_names.delete(self.name)
        all_names << self.name
        return all_names
    end    

end

class Requirement < ActiveRecord::Base
   belongs_to :snippet, :foreign_key => "snippet_id", :class_name => "Snippet"
   belongs_to :required_snippet, :foreign_key => "required_snippet_id", :class_name => "Snippet"
end

rails/app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # Auto generated controllers

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:name, :eval, :code, :run_code, :hide, :example, :language)
    end
end

rails/app/helpers/snippets_helper.rb
module SnippetsHelper
end

rails/app/views/snippets/_form.html.erb
<%= form_for(snippet) do |f| %>
  <% if snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% snippet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :eval %>
    <%= f.check_box :eval %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :hide %>
    <%= f.check_box :hide %>
  </div>

  <div class="field">
    <%= f.label :example %>
    <%= f.text_field :example %>
  </div>

  <div class="field">
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

rails/app/views/snippets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Snippets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Eval</th>
      <th>Code</th>
      <th>Hide</th>
      <th>Example</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= snippet.name %></td>
        <td><%= snippet.eval %></td>
        <td><%= snippet.code %></td>
        <td><%= snippet.hide %></td>
        <td><%= snippet.example %></td>
        <td><%= snippet.language %></td>
        <td><%= link_to 'Show', snippet %></td>
        <td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
        <td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet', new_snippet_path %>

rails/app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form', snippet: @snippet %>

<%= link_to 'Back', snippets_path %>

rails/app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @snippet.name %>
</p>

<p>
  <strong>Eval:</strong>
  <%= @snippet.eval %>
</p>

<p>
  <strong>Code:</strong>
  <%= @snippet.code %>
</p>

<p>
  <strong>Hide:</strong>
  <%= @snippet.hide %>
</p>

<p>
  <strong>Example:</strong>
  <%= @snippet.example %>
</p>

<p>
  <strong>Language:</strong>
  <%= @snippet.language %>
</p>

<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>